### ISSUE TITLE
 Platform error: sensor - Integration 'temperhum' not found.

### ISSUE THREAD

**Issue by Strykar** [rmtsrc/home-assistant-temperhum#1]
HACS is installed and this added as a custom repo in it.
```
Logger: homeassistant.config
Source: config.py:1258
First occurred: 6:29:27 AM (1 occurrences)
Last logged: 6:29:27 AM

Platform error: sensor - Integration 'temperhum' not found.
```
```
Home Assistant

    Core 2024.1.3
    Supervisor 2023.12.0
    Operating System 11.4
    Frontend 20240104.0
```

**Comment by rmtsrc** [comment]
I wasn't able to reproduce this. Have you tried reinstalling the integration via:

1. Add this repos URL to the **Custom repositories** list from the hamburger menu and choose **Integration**.
2. Search for **TEMPerHUM** via the HACS UI and click the **Download** button (bottom left) or select the hamburger menu and select **Redownload**

If this doesn't work try following the manual steps:

> Download the latest [temperhum.zip](https://github.com/rmtsrc/home-assistant-temperhum/releases/latest/download/temperhum.zip) from the [releases page](https://github.com/rmtsrc/home-assistant-temperhum/releases) and extract the contents into your Home Assistants config/custom_components/temperhum folder.

**Comment by Strykar** [comment]
Thanks, Redownload shows the message about it actually downloading post which it works fine, log:
```
Home Assistant Core
[140296940457152] Error handling message: length of value must be at least 1 for dictionary value @ data['statistic_ids']. Got [] (invalid_format) Avi from 192.168.1.10 (Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0)
4:02:14 AM – (ERROR) Home Assistant WebSocket API
Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
4:01:00 AM – (WARNING) helpers/entity.py - message first occurred at 4:01:00 AM and shows up 2 times
Ended unfinished session (id=21 from 2024-01-13 22:29:28.072688)
4:00:58 AM – (WARNING) Recorder
The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
4:00:58 AM – (WARNING) Recorder
```
I've got two of these with one passed through to the HA VM, how do I see the numbers or create a dashboard panel for it?
![image](https://github.com/rmtsrc/home-assistant-temperhum/assets/2946372/e766c42b-d803-4ac3-a8aa-485f7b42965d)

**Comment by rmtsrc** [comment]
After restarting Home Assistant with the new configuration the sensors can be found in the auto generated dashboard or if you've customised it, the sensors can be added by editing your dashboard, adding a new card by entity and searching for **TEMPer**.

However, I've stopped using the TEMPer integrations inside of Home Assistant, as I found this and the official integration were unreliable (for me, but YMMV) and would sometimes stop updating in Home Assistant OS or where giving me an [`usb.core.NoBackendError: No backend available` error](https://github.com/home-assistant/core/issues/105544) when I tried to use the standalone Home Assistant container.

So I've since moved to a more reliable method of using a standalone [TEMPered-webhook](https://github.com/rmtsrc/TEMPered-webhook) which gets the data from the device (via a different device API) outside of Home Assistant and sends it via a webhook.

**Comment by Strykar** [comment]
I did try that in the Dashboard and the only card available is one that shows the Integration is up to date, no temps:
![image](https://github.com/rmtsrc/home-assistant-temperhum/assets/2946372/b8bbb5b4-61a3-4011-84e1-6ef91624019e)

Regarding that error, I am trying to get upstream to support the model so it will work with the default HA Temper - https://github.com/padelt/temper-python/issues/138

**Comment by rmtsrc** [comment]
If you've installed the integration and updated the config to include the `sensor.platform: temperhum` key/value. Then the only other things I can think of might be:

* The device is not connected e.g. if Home Assistant is running inside of a VM you need to update the VM's config to attach the USB device to the guest Home Assistant OS or if its in a container/LXC you need to pass-through the device's location
* It's not detecting the device or the device is not supported, as this plugin also uses the [temper-python](https://github.com/padelt/temper-python) just like the official Home Assistant TEMPer integration, so perhaps until temper-python supports your TEMPer model it might not work and might be worth checking if [TEMPered-webhook](https://github.com/rmtsrc/TEMPered-webhook) picks it up

I've checked what appears in my Home Assistant OS when it's unplugged vs. plugged in and the following should show up on the All Hardware page (Settings > System > Hardware > All Hardware). You also need to enable "Advanced Mode" by clicking on your username (bottom, left) and enabling the toggle.

```
2-1
/dev/input/by-id/usb-RDing_TEMPERHUM1V1.2-event-kbd
event3
hiddev0
hidraw0
hidraw1
usb2
usb3
usbmon2
usbmon3
```

I also just tested on a fresh install of Home Assistant OS in another VM and my device actually appeared as "Unnamed Device" for the temperate and "Unnamed Device humidity", you can click into the settings of each device and rename it and set a custom ID etc.

![Screenshot from 2024-01-14 14-51-27](https://github.com/rmtsrc/home-assistant-temperhum/assets/144435/df4d2f3d-0040-4652-9587-4325b27c863c)

**Comment by Strykar** [comment]
Thanks, if this too depends on `temper-python` this will need to be fixed upstream, same for `TEMPered-webhook`.
The device is listed under `lsusb`, passthrough works fine, I am also passing through a bluetooth dongle.

There is nothing under States, I will close this for now as it needs fixing upstream.
